FROM unitychip-tutorial:v1

RUN pip3 install pytoffee

RUN sudo mkdir tutorial && \
    cd tutorial && \
    sudo git clone https://github.com/OpenXiangShan/XSPdb.git && \
    cd XSPdb && \
    pip3 install -r requirements.txt && \
    cd .. && \
    sudo git clone https://github.com/SFangYy/tutorial_code.git
